### ISSUE TITLE
GetTitles does not work (always return empty result)

### ISSUE THREAD

**Issue by codymanix** [JDBarndt/JustWatch-API#6]
var jw = new JustWatchClient();
var titles = jw.GetTitles(new JustWatchApi.Models.GetTitlesRequest(JustWatchApi.Models.Common.Country.UnitedStates));

All fields in the resulting titles  object are null. I also tried with other countries, no avail.

**Comment by JDBarndt** [comment]
As far as I can tell, `GetTitles` is deprecated and no longer supported by the external API. I have pushed an update that removes this method entirely.

As an alternative, you can call the `GetMovie` or `GetShow` methods to achieve a similar result, albeit one at a time:

```
var client = new JustWatchClient();
var response = client.GetMovie(new GetMovieRequest(Country.UnitedStates, 122337));
```
```
var client = new JustWatchClient();
var response = client.GetShow(new GetShowRequest(Country.UnitedStates, 12));
```

Just like `GetTitles`, you will need an ID to call `GetMovie` and `GetShow`.

If you don't have an ID and are trying to browse through the catalog, use `GetPopular` instead.

**Comment by codymanix** [comment]
Thank you for this information!
